language: generic
sudo: required
dist: trusty
services:
  - docker
script:
  - sudo -E bash build.sh
notifications:
  email: false
env:
  global:
    - TOOLS="bcbio-vc bcbio-rnaseq"
    - secure: "qQ6bJpS+rysr2zu/Lfs1lr2x/wj16Q28gM/axl2ffBeiQIFhJ43STeC+aBpDx+VjtR3uvINvc3VHa4LWaBV+8qNxX+Wc6aHSBScsEULIYYo2WkZySVhG01kY3QM4xGQHTNySXWfs4Hw9RJlK407lCIRGsnKLU9P1J5dODbTGrwjg0kCwtstE6RfICfT60pYfDXbLf/86D+z3/HbDQUMUF4biQlwC4s60sTjq597C3PWo45k2FK5lZW1O6D3m6D54nmgo2k0quhh1PvidEE/ug5mzMrzrAaZKqLJeXXFcNj0XbqaFMwH5K5ZKAXUoKpKTVJyrXwIHfOZDXjtajdDthsOLSRwTMe8stsWIPiQ9ME75X4uZJ7hWDUXFE6i0QIsU7oaUc9pCOfk+D4rO4tPUhbzGbNaLkYdHxLoEhD3IaEzaJRKyjS7ZWGgaQdTw2nc1Z260PVepzBNccWrJnwzn36e9JL6Dd5hFiiWujOs1cUIfGFWXwDnsVVYsQEb00KJuOyHh0lFMxpLIbKSrz1u6277x7lqGuE5WJTbCRU0JvZQySVJTAV2yrGLcwdUnrGWbjpmVX1lI1JWEFvwD90c0lZaSoS2AWX5oHhPAaW9y/xsjECeugKktkTixHdJYWrEYoZASPpAvGOFdSqKjgyB7182bLfM5iMMa4s7SAPofMZA="
