name: bcbio-docker-publish
on:
  push:
    branches:
      - gha
    tags:
      - '*'
jobs:
  build-base:
    env:
      BCBIO_VERSION: 1.2.4
      BCBIO_REVISION: 517b34
      image_name: bcbio-base
      context: builds/base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and publish image to Quay
        uses: docker/build-push-action@v2
        with:
          context: .
          file: builds/base/Dockerfile
          push: true
          tags: |
            quay.io/bcbio-base:1.2.4-517b34
            quay.io/bcbio-base:latest
