name: bcbio-docker-publish
on:
  push:
    branches:
      - gha
    tags:
      - '*'
jobs:
  build-base:
    env:
      BCBIO_VERSION: 1.2.4
      BCBIO_REVISION: 517b34
      image_name: bcbio-base
      context: builds/base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish image to Quay
        uses: docker/build-push-action@v2
        with:
          context: .
          file: builds/base/Dockerfile
          push: false
          tags: |
            bcbio-base:1.2.4-517b34
            bcbio-base:latest
