name: bcbio-docker-publish
on:
  push:
    branches:
      - master
    tags:
      - '*'
env:
  BCBIO_VERSION: 1.2.5
  BCBIO_REVISION: 69eea83
jobs:
  build-base:
    env:
      IMAGE_NAME: bcbio-base
      DOCKERFILE: builds/base/Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and publish image to Quay
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ jobs.bcbio-base.env.DOCKERFILE }}
          push: true
          tags: |
            quay.io/bcbio/${{ jobs.bcbio-base.env.IMAGE_NAME }}:${{ env.BCBIO_VERSION }}-${{ env.BCBIO_REVISION }}
            quay.io/bcbio/${{ jobs.bcbio-base.env.IMAGE_NAME }}:latest
  build-rnaseq:
    env:
      IMAGE_NAME: bcbio-rnaseq
      DOCKERFILE: builds/rnaseq/Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and publish image to Quay
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ jobs.bcbio-rnaseq.env.DOCKERFILE }}
          push: true
          tags: |
            quay.io/bcbio/${{ jobs.bcbio-rnaseq.env.IMAGE_NAME }}:${{ env.BCBIO_VERSION }}-${{ env.BCBIO_REVISION }}
            quay.io/bcbio/${{ jobs.bcbio-rnaseq.env.IMAGE_NAME }}:latest
